# Generated by Django 4.1.1 on 2022-10-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carMake', models.CharField(max_length=250)),
                ('carModel', models.CharField(max_length=250)),
                ('carReg', models.CharField(max_length=250)),
                ('carYear', models.CharField(max_length=250)),
                ('engNumber', models.CharField(max_length=250)),
                ('chassNumber', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='static/images')),
            ],
        ),
    ]
