# Generated by Django 4.1.1 on 2022-10-01 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif_cost', models.IntegerField()),
                ('customs_duty', models.IntegerField()),
                ('delivery_order', models.IntegerField()),
                ('cfs_charges', models.IntegerField()),
                ('kebs', models.IntegerField()),
                ('ntsa', models.IntegerField()),
                ('insurance', models.IntegerField()),
                ('agency', models.IntegerField()),
                ('transport', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
            ],
        ),
    ]
