# Generated by Django 4.1.1 on 2022-10-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_profit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profit',
            old_name='total_cost',
            new_name='car_cost',
        ),
    ]
